### ISSUE TITLE
 listen tcp :22: bind: address already in use

### ISSUE THREAD

**Issue by Zkmani** [joushou/sshmuxd#11] opened 2016-05-17 04:21 UTC
I have a problem, please help me check it.

```
sh-3.2# ./sshmuxd example_conf.json
panic: listen tcp :22: bind: address already in use

goroutine 1 [running]:
main.main()
    /Users/zhangkun/wk/go/src/github.com/joushou/sshmuxd/main.go:184 +0x4b0

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
    /usr/local/go/src/runtime/asm_amd64.s:1721 +0x1
sh-3.2# cat 
.git/              .gitignore         LICENSE            README.md          authkeys           example_conf.json  hostkey            main.go            sshmuxd
sh-3.2# cat example_conf.json 
{
   "address": ":22",
   "hostkey": "hostkey",
   "authkeys": "authkeys",
   "hosts": [
      {
         "address": "10.10.11.14:22",
         "users": [ "root" ]
      },
      {
         "address": "public.example.com:22",
         "noAuth": true
      },
      {
         "address": "secret.example.com:22",
         "users": [ "me" ]
      }
   ]
}

sh-3.2# 

```

**Comment by Zkmani** [comment] 2016-05-17 11:04
The above problems are solved, but the problem appeared below

```
ZhangKundeMacBook-Pro:github.com zhangkun$ ssh -oProxyCommand="ssh -W 127.0.0.1:2222 127.0.0.1" root@10.10.11.14
The authenticity of host '127.0.0.1 (127.0.0.1)' can't be established.
RSA key fingerprint is 3b:4d:18:98:84:c9:55:0b:c6:88:7b:4d:8f:d3:ac:af.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '127.0.0.1' (RSA) to the list of known hosts.
Password:
The authenticity of host '10.10.11.14 (<no hostip for proxy command>)' can't be established.
RSA key fingerprint is be:db:98:3d:82:f3:98:10:55:ae:73:bd:10:05:39:29.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '10.10.11.14' (RSA) to the list of known hosts.
Welcome to sshmux, root
    [0] 10.10.11.14:22
    [1] 10.10.11.14:22
Please select remote server: 0
Connecting to 10.10.11.14:22
Warning: ssh server tried agent forwarding.
Warning: this is probably a break-in attempt by a malicious server.

====== sshmux ======
sshmux requires either agent forwarding or secure channel forwarding.
Either enable agent forwarding (-A), or use a ssh -W proxy command.
For more info, see the sshmux wiki.
Connection to 10.10.11.14 closed.
Killed by signal 1.
ZhangKundeMacBook-Pro:github.com zhangkun$ 
```

**Comment by kennylevinsen** [comment] 2016-05-17 22:06
The first issue was obviously a port conflict. I'm glad you sorted it out - I was admittedly a bit lazy with regards to error mesages when I wrote this.

The second issue seems to be a broken `ssh -W command`. Assuming you run sshmuxd on port 2222, the command would be:

```
ssh -oProxyCommand="ssh -W %h:%p 127.0.0.1:2222" root@10.10.11.14
```

You tried to use your local SSH server to jump to sshmuxd because if the broken ssh -W command. The README also shows the command with two example hostnames.

Can you try the corrected ssh command, and see if that works?

**Comment by Zkmani** [comment] 2016-05-18 10:21
hi accordance with the wording you still have problems.

```
ZhangKundeMacBook-Pro:sshmuxd zhangkun$ ssh -oProxyCommand="ssh -W %h:%p 172.16.159.181:2222" root@10.10.11.14
ssh: Could not resolve hostname 172.16.159.181:2222: nodename nor servname provided, or not known
ssh_exchange_identification: Connection closed by remote host
ZhangKundeMacBook-Pro:sshmuxd zhangkun$ ssh -oProxyCommand="ssh -W %h:%p 172.16.159.181:2222" 10.10.11.14
ssh: Could not resolve hostname 172.16.159.181:2222: nodename nor servname provided, or not known
ssh_exchange_identification: Connection closed by remote host
```

**Comment by kennylevinsen** [comment] 2016-05-18 11:24
Oh, I'm sorry - I made a mistake in the way you specify ports for SSH! I was a bit tired, and just shuffled your ProxyCommand around. Didn't realise that the port would be problematic. :)

"ssh -p2222 -W %h:%p 172.16.159.181", or "ssh -oPort=2222 -W %h:%p 172.16.159.181", depending on which syntax you prefer.

The SSH manpages also further specify how this works (It's not sshmux specific).

**Comment by Zkmani** [comment] 2016-05-18 11:45
Very happy to help me solve the problem, but does not seem to go through your program to do the jump

```
ZhangKundeMacBook-Pro:sshmuxd zhangkun$ ssh -oProxyCommand="ssh -p2222  -W %h:%p 172.16.159.181" root@10.10.11.14

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed May 18 19:49:02 2016 from 10.10.16.223
```

**Comment by Zkmani** [comment] 2016-05-18 11:56
I found another way but there is a problem

```
ZhangKundeMacBook-Pro:sshmuxd zhangkun$ ssh -A zhangkun@172.16.159.181 -p 2222
Welcome to sshmux, zhangkun
    [0] 10.10.11.14:22
    [1] 10.10.11.13:22
Please select remote server: 0
Connecting to 10.10.11.14:22
Connect failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
Connection to 172.16.159.181 closed.
```

**Comment by kennylevinsen** [comment] 2016-05-18 12:17
This seemed to work though - it prints the motd from your debian box at 10.10.11.14, didn't it?

Best regards,
Kenny Levinsen

**Comment by kennylevinsen** [comment] 2016-05-18 12:19
In this case, you're not permitting public key login to the box you're jumping to it seems.

Best regards,
Kenny Levinsen

**Comment by Zkmani** [comment] 2016-05-18 12:30
I did not see you jump interface，After your server does not seem to jump, and anybody can log on

```
root@debian8:~/ssh/src/github.com/joushou/sshmuxd# cat example_conf.json 
{
   "address": ":2222",
   "hostkey": "/root/ssh/src/github.com/joushou/sshmuxd/hostkey",
   "authkeys": "/root/ssh/src/github.com/joushou/sshmuxd/authkeys",
   "hosts": [
      {
         "address": "10.10.11.14:22",
         "users": [ "zhangkun","root" ],
         "noAuth": true
      },
      {
         "address": "10.10.11.13:22",
         "users": [ "root" ],
         "noAuth": true
      }
   ]
}
```

**Comment by kennylevinsen** [comment] 2016-05-18 12:39
10.10.11.14:22 rejects your local private key and/or does not allow pubkey login, and thus using ssh -A fails. I have not implemented password (keyboardinteractive) support.

Your try with ssh -W printed a debian message, which sounds like sshmux did it's thing - does the shell not show up? In this case, maybe try adding a different box to test to see if it shoes up there?

As for your config, you set "noAuth" to true on both your hosts, which means that anyone will be permitted to login. I think you want it set to false.

Best regards,
Kenny Levinsen

**Comment by kennylevinsen** [comment] 2016-05-18 13:03
Sorry, just did some debugging. As for when you tried -A, the problem is probably that you didn't have an ssh-agent running. Start it with

ssh-agent -s
ssh-add

If your agent is missing, it'll just show as you not having any private keys available, thus saying it tried publickey auth but failed. I can add a warning for this.

**Comment by kennylevinsen** [comment] 2016-05-24 13:43
Does things work for you now? If so, please close the issue.

**Closed as completed** 2016-05-27 06:03 UTC
